name: Update

on:
  # every Sunday at 00:00 UTC
  # https://crontab.guru/#0_0_*_*_0
  # schedule:
  #   - cron: '0 0 * * 0'

  # https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      # necessary to open PR
      # https://github.com/peter-evans/create-pull-request#action-inputs
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: configure git user
        run: |
          git config user.name 'Conda Bot'
          git config user.email '18747875+conda-bot@users.noreply.github.com'

      - name: combine recent durations from artifacts
        uses: conda/actions/combine-durations@combine-durations

      - name: commit updated durations
        run: git add . && git commit --message "Update test durations" || true

      - name: sync & template files
        uses: conda/actions/template-files@template-files

      - name: commit templated files
        run: git add . && git commit --message "Sync files" || true

      - name: create update PR
        uses: peter-evans/create-pull-request@v5
        with:
          push-to-fork: kenodegard-bot/${{ github.event.repository.name }}
          token: ${{ secrets.SYNC_TOKEN }}
          branch: update
          delete-branch: true
          title: ðŸ¤– Update
          body: |
            [update.yml]: ${{ github.server_url }}/${{ github.repository }}/blob/main/.github/workflows/update.yml

            This PR was created automatically by the [`update.yml`][update.yml] workflow.
