conda-sandbox/infrastructure:
  # - .github/workflows/update.yml

  # - CODE_OF_CONDUCT.md

  - src: templates/HOW_WE_USE_GITHUB.md
    dst: HOW_WE_USE_GITHUB.md

  - src: templates/issues/bug.yml
    dst: .github/ISSUE_TEMPLATE/0_bug.yml

  - src: templates/issues/feature.yml
    dst: .github/ISSUE_TEMPLATE/1_feature.yml

  - src: templates/issues/epic.yml
    dst: .github/ISSUE_TEMPLATE/epic.yml

  # uncomment to include checklist PR template
  - src: templates/pull_requests/news_tests_docs.md
    dst: .github/PULL_REQUEST_TEMPLATE.md

  # uncomment to include simple PR template
  # - src: templates/pull_requests/base.md
  #   dst: .github/PULL_REQUEST_TEMPLATE.md

  # uncomment to include rever release files
  # - src: templates/releases/RELEASE.md
  #   dst: RELEASE.md

  # - src: templates/releases/rever.xsh
  #   dst: rever.xsh

  # - src: templates/releases/TEMPLATE
  #   dst: news/TEMPLATE
